import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Spline from '@splinetool/react-spline/next';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<Spline
            scene="https://prod.spline.design/VdnaWUzwVsD3tBUO/scene.splinecode"
            loading-anim-type="spinner-small-dark" 
            style={{
              position: 'absolute',
          //     left: 0,
          //     top: 0,
          //     right: 50,
              width: '100%',
              height: '100vh',
              zIndex: -1,
          }} 
          />  
        {children}
      </body>
    </html>
  );
}
